# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mvtbTS0C_0yro4-IN6DQi2zWoyklSLAr
"""

import pandas as pd
import numpy as np
import io
import matplotlib.pyplot as mlp
import seaborn as sb
import sklearn as sk
from google.colab import files
uploaded=files.upload()

datafile=pd.read_csv("Social_Network_Ads.csv")

datafile

m=datafile.iloc[:,[2,3]].Values
n=datafile.iloc[:,4].values